workspace(name = "rules_android_lint_examples")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Android

http_archive(
    name = "build_bazel_rules_android",
    sha256 = "cd06d15dd8bb59926e4d65f9003bfc20f9da4b2519985c27e190cddc8b7a7806",
    strip_prefix = "rules_android-0.1.1",
    urls = ["https://github.com/bazelbuild/rules_android/archive/v0.1.1.zip"],
)

load("@build_bazel_rules_android//android:rules.bzl", "android_sdk_repository")

android_sdk_repository(name = "androidsdk")

# Java

RULES_JAVA_VERSION = "5.4.0"

RULES_JAVA_SHA = "9b87757af5c77e9db5f7c000579309afae75cf6517da745de01ba0c6e4870951"

http_archive(
    name = "rules_java",
    sha256 = RULES_JAVA_SHA,
    url = "https://github.com/bazelbuild/rules_java/releases/download/{v}/rules_java-{v}.tar.gz".format(v = RULES_JAVA_VERSION),
)

# Maven

RULES_JVM_EXTERNAL = "4.5"

RULES_JVM_EXTERNAL_SHA = "b17d7388feb9bfa7f2fa09031b32707df529f26c91ab9e5d909eb1676badd9a6"

http_archive(
    name = "rules_jvm_external",
    sha256 = RULES_JVM_EXTERNAL_SHA,
    strip_prefix = "rules_jvm_external-{}".format(RULES_JVM_EXTERNAL),
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/{v}.zip".format(v = RULES_JVM_EXTERNAL),
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "androidx.activity:activity:1.6.0",
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)

# # Kotlin

rules_kotlin_version = "1.7.1"

rules_kotlin_sha = "fd92a98bd8a8f0e1cdcb490b93f5acef1f1727ed992571232d33de42395ca9b3"

http_archive(
    name = "io_bazel_rules_kotlin",
    sha256 = rules_kotlin_sha,
    urls = ["https://github.com/bazelbuild/rules_kotlin/releases/download/v%s/rules_kotlin_release.tgz" % rules_kotlin_version],
)

load("@io_bazel_rules_kotlin//kotlin:repositories.bzl", "kotlin_repositories")

kotlin_repositories()

load("@io_bazel_rules_kotlin//kotlin:core.bzl", "kt_register_toolchains")

kt_register_toolchains()

# # Directly load the lint rules from the parent repo.

local_repository(
    name = "rules_android_lint",
    path = "../",
)

# Lint Dependencies

load("@rules_android_lint//lint:dependencies.bzl", "rules_android_lint_dependencies")

rules_android_lint_dependencies()

load("@rules_android_lint//lint:toolchains.bzl", "rules_android_lint_toolchains")

rules_android_lint_toolchains()
