py_binary(
    name = "test_runner_executable",
    srcs = ["test_runner_executable.py"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_runner_template",
    srcs = ["test_runner_template.bash"],
    visibility = ["//visibility:public"],
)
