name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  # Cancel previous actions from the same PR: https://stackoverflow.com/a/72408109
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        bzlmod: [true]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v4
      - name: Mount bazel caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: bazel-cache-${{ hashFiles('**/BUILD.bazel', '**/*.bzl', 'WORKSPACE', 'WORKSPACE.bazel') }}
          restore-keys: bazel-cache-
      - name: "Setup Bazelisk"
        uses: bazelbuild/setup-bazelisk@v2
      - name: "Running tests //..."
        run: bazel test //... --enable_bzlmod=${{ matrix.bzlmod }}
  integration-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        bzlmod: [true]
        directory: [examples/simple-android]
        strategy: [local, worker]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v4
      - name: Mount bazel caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: bazel-cache-${{ hashFiles('**/BUILD.bazel', '**/*.bzl', 'WORKSPACE', 'WORKSPACE.bazel') }}
          restore-keys: bazel-cache-
      - name: "Setup Bazelisk"
        uses: bazelbuild/setup-bazelisk@v2
      - name: "Running integration tests ${{ matrix.directory }}"
        working-directory: ${{ matrix.directory }}
        run: bazel test //... --enable_bzlmod=${{ matrix.bzlmod }} --strategy=AndroidLint=${{ matrix.strategy }}
