name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  # Cancel previous actions from the same PR or branch except 'main' branch.
  # See https://docs.github.com/en/actions/using-jobs/using-concurrency and https://docs.github.com/en/actions/learn-github-actions/contexts for more info.
  group: concurrency-group::${{ github.workflow }}::${{ github.event.pull_request.number > 0 && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}${{ github.ref_name == 'main' && format('::{0}', github.run_id) || ''}}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        bzlmod: [true]
        bazel_version: ["7.4.1", "8.0.1"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v4
      - name: Mount bazel caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
          key: bazel-cache-${{ hashFiles('**/BUILD.bazel', '**/*.bzl', 'WORKSPACE', 'WORKSPACE.bazel') }}
          restore-keys: bazel-cache-
      - name: "Setup Bazelisk"
        uses: bazelbuild/setup-bazelisk@v3
      - name: "Running tests //..."
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel_version }}
        run: bazel test //... --enable_bzlmod=${{ matrix.bzlmod }}
  integration-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        bzlmod: [true]
        directory: [examples/simple-android]
        strategy: [local, worker]
        bazel_version: ["7.4.1", "8.0.1"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v4
      - name: Mount bazel caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
          key: bazel-cache-${{ hashFiles('**/BUILD.bazel', '**/*.bzl', 'WORKSPACE', 'WORKSPACE.bazel') }}
          restore-keys: bazel-cache-
      - name: "Setup Bazelisk"
        uses: bazelbuild/setup-bazelisk@v3
      - name: "Running integration tests ${{ matrix.directory }}"
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel_version }}
        working-directory: ${{ matrix.directory }}
        run: bazel test //... --enable_bzlmod=${{ matrix.bzlmod }} --strategy=AndroidLint=${{ matrix.strategy }}
