name: CI

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  buildifier:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v3.3.0
      - name: "Install JDK 11"
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Setup Bazelisk"
        uses: bazelbuild/setup-bazelisk@v2
      - name: "Linting Starlark"
        run: bazel run @buildifier_prebuilt//:buildifier -- -mode check -lint warn -r .
      - name: "Lint Shell files"
        run: ./scripts/lint-shell-files.sh

  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v3.3.0
      - name: "Install JDK 11"
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Setup Bazelisk"
        uses: bazelbuild/setup-bazelisk@v2
      - name: "Building examples"
        run: ./scripts/build-examples.sh